version: "1.0"

services:
  flask_app:
    container_name: flask_app
    image: sel-todo-app-flask
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres_db:5432/postgres
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./1-initdb.sql:/docker-entrypoint-initdb.d/1-initdb.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=seliscool
      - POSTGRES_DB=todoapp

volumes:
  postgres_data: {}