name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        working-directory: ./sel-todo-app
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: ./sel-todo-app
        run: npx playwright install --with-deps
      - name: Build production
        working-directory: ./sel-todo-app
        run: npm run build
      - name: Run Playwright tests
        working-directory: ./sel-todo-app
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: sel-todo-app/playwright-report/
          retention-days: 30
